name: xaj-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - numba
  - pandas
  - scikit-learn
  - deap
  - spotpy=1.5.14
  - seaborn
  - tqdm
  - pyarrow
  - hydroerr
  - xarray
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - tensorboard
  - sphinx
  - pytest
  - black
  - pip
  - pip:
    - hydrodataset
    # config for deep learning
    - hydra-core
    - accelerate
