data_cfgs:
  basin_ids:
  - songliao_21401550
  data_source_path: D:\data\waterism\datasets-interim\songliaorrevent
  data_source_type: floodevent
  time_range:
  - '1960-01-01'
  - '2024-12-31'
  variables:
  - P_eff
  - Q_obs_eff
  warmup_length: 480
evaluation_cfgs:
  metrics:
  - RMSE
  - NSE
  - flood_peak_error
  - flood_volume_error
  plot_results: true
  save_results: true
model_cfgs:
  model_name: unit_hydrograph
  model_params:
    apply_peak_penalty: true
    n_uh: 24
    net_rain_name: P_eff
    obs_flow_name: Q_obs_eff
    peak_violation_weight: 10000.0
    smoothing_factor: 0.1
training_cfgs:
  algorithm_name: scipy_minimize
  algorithm_params:
    max_iterations: 500
    method: SLSQP
  experiment_name: unit_hydrograph_experiment
  loss_config:
    obj_func: RMSE
    type: event_based
  output_dir: results
  random_seed: 1234
