on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: Linux build
jobs:
    py-check:
        runs-on: ${{ matrix.config.os }}
        name: ${{ matrix.config.os }} (${{ matrix.config.py }})
        strategy:
            fail-fast: false
            matrix:
                config:
                    - { os: ubuntu-latest, py: "3.11" }
        env:
            UV_HTTP_TIMEOUT: 300
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                  enable-cache: true
                  cache-dependency-glob: "**/pyproject.toml"
            - name: Set up Python ${{ matrix.config.py }}
              run: uv python install ${{ matrix.config.py }}
            - name: Install GDAL
              run: |
                  uv pip install --no-cache-dir Cython
                  uv pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  uv run python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  uv sync --all-extras
            - name: Create hydro_setting.yml
              run: |
                  echo 'local_data_path:' > hydro_setting.yml
                  echo '  datasets-origin: /home/runner/.cache/' >> hydro_setting.yml
                  sudo cp hydro_setting.yml /home/runner/hydro_setting.yml
                # Add other settings here as required
            - name: PKG-TEST
              run: |
                  uv run pytest test/test_data_preprocess.py
                #   uv run pytest test/test_xaj.py
                #   uv run pytest test/test_gr4j.py
                #   uv run pytest test/test_hymod.py

